language: en
pipeline:
- name: SpacyNLP
- name: WhitespaceTokenizer
  "case_sensitive": False
- name: SpacyEntityExtractor
  entities:
  - PERSON
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
  OOV_token: oov
  analyzer: word
  min_ngram: 1
  max_ngram: 4
- name: EmbeddingIntentClassifier
  epochs: 300
- name: ResponseSelector
  retrieval_intent: out_of_scope
  epochs: 300
policies:
- name: KerasPolicy
  epochs: 300
- name: TwoStageFallbackPolicy
  nlu_threshold: 0.3
  ambiguity_threshold: 0.1
  core_threshold: 0.3
  fallback_core_action_name: action_default_fallback
  fallback_nlu_action_name: action_default_fallback
  deny_suggestion_intent_name: out_of_scope
- name: MemoizationPolicy
- name: FormPolicy
- name: MappingPolicy
